# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.8/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.8/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vericate/Development/clion/lllengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vericate/Development/clion/lllengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.8/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.8/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vericate/Development/clion/lllengine/CMakeFiles /Users/vericate/Development/clion/lllengine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vericate/Development/clion/lllengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lllengine

# Build rule for target.
lllengine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lllengine
.PHONY : lllengine

# fast build rule for target.
lllengine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/build
.PHONY : lllengine/fast

src/core/app.o: src/core/app.cpp.o
.PHONY : src/core/app.o

# target to build an object file
src/core/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/app.cpp.o
.PHONY : src/core/app.cpp.o

src/core/app.i: src/core/app.cpp.i
.PHONY : src/core/app.i

# target to preprocess a source file
src/core/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/app.cpp.i
.PHONY : src/core/app.cpp.i

src/core/app.s: src/core/app.cpp.s
.PHONY : src/core/app.s

# target to generate assembly for a file
src/core/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/app.cpp.s
.PHONY : src/core/app.cpp.s

src/core/app_gof.o: src/core/app_gof.cpp.o
.PHONY : src/core/app_gof.o

# target to build an object file
src/core/app_gof.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/app_gof.cpp.o
.PHONY : src/core/app_gof.cpp.o

src/core/app_gof.i: src/core/app_gof.cpp.i
.PHONY : src/core/app_gof.i

# target to preprocess a source file
src/core/app_gof.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/app_gof.cpp.i
.PHONY : src/core/app_gof.cpp.i

src/core/app_gof.s: src/core/app_gof.cpp.s
.PHONY : src/core/app_gof.s

# target to generate assembly for a file
src/core/app_gof.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/app_gof.cpp.s
.PHONY : src/core/app_gof.cpp.s

src/core/ecs/entity.o: src/core/ecs/entity.cpp.o
.PHONY : src/core/ecs/entity.o

# target to build an object file
src/core/ecs/entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/ecs/entity.cpp.o
.PHONY : src/core/ecs/entity.cpp.o

src/core/ecs/entity.i: src/core/ecs/entity.cpp.i
.PHONY : src/core/ecs/entity.i

# target to preprocess a source file
src/core/ecs/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/ecs/entity.cpp.i
.PHONY : src/core/ecs/entity.cpp.i

src/core/ecs/entity.s: src/core/ecs/entity.cpp.s
.PHONY : src/core/ecs/entity.s

# target to generate assembly for a file
src/core/ecs/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/ecs/entity.cpp.s
.PHONY : src/core/ecs/entity.cpp.s

src/core/ecs_renderer.o: src/core/ecs_renderer.cpp.o
.PHONY : src/core/ecs_renderer.o

# target to build an object file
src/core/ecs_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/ecs_renderer.cpp.o
.PHONY : src/core/ecs_renderer.cpp.o

src/core/ecs_renderer.i: src/core/ecs_renderer.cpp.i
.PHONY : src/core/ecs_renderer.i

# target to preprocess a source file
src/core/ecs_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/ecs_renderer.cpp.i
.PHONY : src/core/ecs_renderer.cpp.i

src/core/ecs_renderer.s: src/core/ecs_renderer.cpp.s
.PHONY : src/core/ecs_renderer.s

# target to generate assembly for a file
src/core/ecs_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/ecs_renderer.cpp.s
.PHONY : src/core/ecs_renderer.cpp.s

src/core/renderer.o: src/core/renderer.cpp.o
.PHONY : src/core/renderer.o

# target to build an object file
src/core/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/renderer.cpp.o
.PHONY : src/core/renderer.cpp.o

src/core/renderer.i: src/core/renderer.cpp.i
.PHONY : src/core/renderer.i

# target to preprocess a source file
src/core/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/renderer.cpp.i
.PHONY : src/core/renderer.cpp.i

src/core/renderer.s: src/core/renderer.cpp.s
.PHONY : src/core/renderer.s

# target to generate assembly for a file
src/core/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/core/renderer.cpp.s
.PHONY : src/core/renderer.cpp.s

src/graphic/camera.o: src/graphic/camera.cpp.o
.PHONY : src/graphic/camera.o

# target to build an object file
src/graphic/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/camera.cpp.o
.PHONY : src/graphic/camera.cpp.o

src/graphic/camera.i: src/graphic/camera.cpp.i
.PHONY : src/graphic/camera.i

# target to preprocess a source file
src/graphic/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/camera.cpp.i
.PHONY : src/graphic/camera.cpp.i

src/graphic/camera.s: src/graphic/camera.cpp.s
.PHONY : src/graphic/camera.s

# target to generate assembly for a file
src/graphic/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/camera.cpp.s
.PHONY : src/graphic/camera.cpp.s

src/graphic/glextensions.o: src/graphic/glextensions.cpp.o
.PHONY : src/graphic/glextensions.o

# target to build an object file
src/graphic/glextensions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/glextensions.cpp.o
.PHONY : src/graphic/glextensions.cpp.o

src/graphic/glextensions.i: src/graphic/glextensions.cpp.i
.PHONY : src/graphic/glextensions.i

# target to preprocess a source file
src/graphic/glextensions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/glextensions.cpp.i
.PHONY : src/graphic/glextensions.cpp.i

src/graphic/glextensions.s: src/graphic/glextensions.cpp.s
.PHONY : src/graphic/glextensions.s

# target to generate assembly for a file
src/graphic/glextensions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/glextensions.cpp.s
.PHONY : src/graphic/glextensions.cpp.s

src/graphic/shader.o: src/graphic/shader.cpp.o
.PHONY : src/graphic/shader.o

# target to build an object file
src/graphic/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/shader.cpp.o
.PHONY : src/graphic/shader.cpp.o

src/graphic/shader.i: src/graphic/shader.cpp.i
.PHONY : src/graphic/shader.i

# target to preprocess a source file
src/graphic/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/shader.cpp.i
.PHONY : src/graphic/shader.cpp.i

src/graphic/shader.s: src/graphic/shader.cpp.s
.PHONY : src/graphic/shader.s

# target to generate assembly for a file
src/graphic/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/shader.cpp.s
.PHONY : src/graphic/shader.cpp.s

src/graphic/texture.o: src/graphic/texture.cpp.o
.PHONY : src/graphic/texture.o

# target to build an object file
src/graphic/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/texture.cpp.o
.PHONY : src/graphic/texture.cpp.o

src/graphic/texture.i: src/graphic/texture.cpp.i
.PHONY : src/graphic/texture.i

# target to preprocess a source file
src/graphic/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/texture.cpp.i
.PHONY : src/graphic/texture.cpp.i

src/graphic/texture.s: src/graphic/texture.cpp.s
.PHONY : src/graphic/texture.s

# target to generate assembly for a file
src/graphic/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/graphic/texture.cpp.s
.PHONY : src/graphic/texture.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lllengine.dir/build.make CMakeFiles/lllengine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lllengine"
	@echo "... src/core/app.o"
	@echo "... src/core/app.i"
	@echo "... src/core/app.s"
	@echo "... src/core/app_gof.o"
	@echo "... src/core/app_gof.i"
	@echo "... src/core/app_gof.s"
	@echo "... src/core/ecs/entity.o"
	@echo "... src/core/ecs/entity.i"
	@echo "... src/core/ecs/entity.s"
	@echo "... src/core/ecs_renderer.o"
	@echo "... src/core/ecs_renderer.i"
	@echo "... src/core/ecs_renderer.s"
	@echo "... src/core/renderer.o"
	@echo "... src/core/renderer.i"
	@echo "... src/core/renderer.s"
	@echo "... src/graphic/camera.o"
	@echo "... src/graphic/camera.i"
	@echo "... src/graphic/camera.s"
	@echo "... src/graphic/glextensions.o"
	@echo "... src/graphic/glextensions.i"
	@echo "... src/graphic/glextensions.s"
	@echo "... src/graphic/shader.o"
	@echo "... src/graphic/shader.i"
	@echo "... src/graphic/shader.s"
	@echo "... src/graphic/texture.o"
	@echo "... src/graphic/texture.i"
	@echo "... src/graphic/texture.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

